spring:
  profiles:
    active: local

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialization-mode: always

    data: classpath:db/h2/data.sql
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties.hibernate.format_sql: true
    properties.hibernate.use_sql_comments: false